# Generated by Django 3.1.2 on 2020-10-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='class_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='webapp.class'),
        ),
    ]
